### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by Gvinaxu** [zlq4863947/triangular-arbitrage#41]
在Ubuntu18.04执行npm install 报错
`
> leveldown@2.1.1 install /home/gvinaxu/PycharmProjects/triangular-arbitrage/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 platform=linux)
gyp WARN download ignoring invalid "proxy" config setting: "socks5://127.0.0.1:1080"
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: tunneling socket could not be established, cause=socket hang up
gyp ERR! stack     at ClientRequest.onError (/home/gvinaxu/node/lib/node_modules/npm/node_modules/tunnel-agent/index.js:177:17)
gyp ERR! stack     at Object.onceWrapper (events.js:277:13)
gyp ERR! stack     at ClientRequest.emit (events.js:189:13)
gyp ERR! stack     at Socket.socketOnEnd (_http_client.js:426:9)
gyp ERR! stack     at Socket.emit (events.js:194:15)
gyp ERR! stack     at endReadableNT (_stream_readable.js:1125:12)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Linux 4.15.0-46-generic
gyp ERR! command "/home/gvinaxu/node/bin/node" "/home/gvinaxu/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gvinaxu/PycharmProjects/triangular-arbitrage/node_modules/leveldown
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN triangular-arbitrage@0.1.1 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@2.1.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gvinaxu/.npm/_logs/2019-03-29T05_11_23_549Z-debug.log

`

**Comment by zlq4863947** [comment]
@Gvinaxu  `npm install -g windows-build-tools` 执行一下这个试试？
