### ISSUE TITLE
A rest parameter must be array type

### ISSUE THREAD

**Issue by geeks121** [zlq4863947/triangular-arbitrage#45]
I have same issue in WSL running ubuntu and in Windows OS
here is error when i start with "npm start"

`node_modules/ccxt/ccxt.d.ts:360:26 - error TS2370: A rest parameter must be of an array type.

360         cancelAllOrders (...args: any): Promise<any>; // TODO: add function signatures
                             ~~~~~~~~~~~~


node_modules/ccxt/ccxt.d.ts:362:23 - error TS2370: A rest parameter must be of an array type.

362         cancelOrders (...args: any): Promise<any>; // TODO: add function signatures
                          ~~~~~~~~~~~~

node_modules/ccxt/ccxt.d.ts:372:18 - error TS2370: A rest parameter must be of an array type.

372         deposit (...args: any): Promise<any>; // TODO: add function signatures
                     ~~~~~~~~~~~~


node_modules/ccxt/ccxt.d.ts:387:27 - error TS2370: A rest parameter must be of an array type.

387         fetchFundingFees (...args: any): Promise<any>; // TODO: add function signatures
                              ~~~~~~~~~~~~

node_modules/ccxt/ccxt.d.ts:388:27 - error TS2370: A rest parameter must be of an array type.

388         fetchL2OrderBook (...args: any): Promise<any>; // TODO: add function signatures
                              ~~~~~~~~~~~~


node_modules/ccxt/ccxt.d.ts:389:22 - error TS2370: A rest parameter must be of an array type.

389         fetchLedger (...args: any): Promise<any>; // TODO: add function signatures
                         ~~~~~~~~~~~~

node_modules/ccxt/ccxt.d.ts:396:26 - error TS2370: A rest parameter must be of an array type.

396         fetchOrderBooks (...args: any): Promise<any>; // TODO: add function signatures
                             ~~~~~~~~~~~~


node_modules/ccxt/ccxt.d.ts:399:22 - error TS2370: A rest parameter must be of an array type.

399         fetchStatus (...args: any): Promise<any>; // TODO: add function signatures
                         ~~~~~~~~~~~~

node_modules/ccxt/ccxt.d.ts:405:26 - error TS2370: A rest parameter must be of an array type.

405         fetchTradingFee (...args: any): Promise<any>; // TODO: add function signatures
                             ~~~~~~~~~~~~


node_modules/ccxt/ccxt.d.ts:406:27 - error TS2370: A rest parameter must be of an array type.

406         fetchTradingFees (...args: any): Promise<any>; // TODO: add function signatures
                              ~~~~~~~~~~~~

node_modules/ccxt/ccxt.d.ts:407:29 - error TS2370: A rest parameter must be of an array type.

407         fetchTradingLimits (...args: any): Promise<any>; // TODO: add function signatures
                                ~~~~~~~~~~~~


src/lib/api-handler.ts:41:72 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.

41     return await api.createOrder(order.symbol, order.type, order.side, String(order.amount), String(order.price));
                                                                          ~~~~~~~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! triangular-arbitrage@0.1.1 prepare: `npm run rm && tsc -p tsconfig.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the triangular-arbitrage@0.1.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ozhy/.npm/_logs/2020-06-04T01_08_55_386Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! triangular-arbitrage@0.1.1 start: `npm run prepare && node runner.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the triangular-arbitrage@0.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ozhy/.npm/_logs/2020-06-04T01_08_55_508Z-debug.log`

**Comment by geeks121** [comment]
and here is the log

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'prepare' ]
2 info using npm@6.14.5
3 info using node@v13.14.0
4 verbose run-script [ 'prepare' ]
5 info lifecycle triangular-arbitrage@0.1.1~prepare: triangular-arbitrage@0.1.1
6 verbose lifecycle triangular-arbitrage@0.1.1~prepare: unsafe-perm in lifecycle true
7 verbose lifecycle triangular-arbitrage@0.1.1~prepare: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ozhy/node-bot/triangular-arbitrage/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ozhy/node-bot/triangular-arbitrage/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
8 verbose lifecycle triangular-arbitrage@0.1.1~prepare: CWD: /home/ozhy/node-bot/triangular-arbitrage
9 silly lifecycle triangular-arbitrage@0.1.1~prepare: Args: [ '-c', 'npm run rm && tsc -p tsconfig.json' ]
10 silly lifecycle triangular-arbitrage@0.1.1~prepare: Returned: code: 2  signal: null
11 info lifecycle triangular-arbitrage@0.1.1~prepare: Failed to exec prepare script
12 verbose stack Error: triangular-arbitrage@0.1.1 prepare: `npm run rm && tsc -p tsconfig.json`
12 verbose stack Exit status 2
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
12 verbose stack     at EventEmitter.emit (events.js:315:20)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1026:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13 verbose pkgid triangular-arbitrage@0.1.1
14 verbose cwd /home/ozhy/node-bot/triangular-arbitrage
15 verbose Linux 4.19.84-microsoft-standard
16 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "prepare"
17 verbose node v13.14.0
18 verbose npm  v6.14.5
19 error code ELIFECYCLE
20 error errno 2
21 error triangular-arbitrage@0.1.1 prepare: `npm run rm && tsc -p tsconfig.json`
21 error Exit status 2
22 error Failed at the triangular-arbitrage@0.1.1 prepare script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 2, true ]
